.PHONY: tidy
tidy:
	go mod tidy
	go fmt ./...

.PHONY: generate
generate:
	go generate ./...
	go fmt ./...
	sed -i '' 's/int \[\]/Int \[\]/g' ./so24/**/*.gen.go
	
.PHONY: check
check:
	go vet ./...
	go tool github.com/golangci/golangci-lint/cmd/golangci-lint run ./...
	go tool honnef.co/go/tools/cmd/staticcheck ./...

